export interface ReactiveRuntimeThresholds {
  ownerLeaseTtlMs: number;
  ownerRenewIntervalMs: number;
  ownerSweepIntervalMs: number;
  symbolRefreshIntervalMs: number;
  healthPublishIntervalMs: number;
  streamTickMaxAgeMs: number;
  streamHeartbeatMaxAgeMs: number;
  streamHealthTtlMs: number;
  streamWarmupTicks: number;
  wsPingIntervalMs: number;
  wsPongTimeoutMs: number;
  botActionLeaseTtlMs: number;
  degradedNotifyAfterMs: number;
  trailingPersistIntervalMs: number;
  entryFillProbeDebounceMs: number;
  coordinationCommandTimeoutMs: number;
  coordinationBootstrapTimeoutMs: number;
  userStreamOwnerLeaseTtlMs: number;
  userStreamOwnerRenewIntervalMs: number;
  userStreamSweepIntervalMs: number;
  userStreamSubscriptionRefreshIntervalMs: number;
  userStreamKeyExpiryMs: number;
  userStreamKeepaliveIntervalMs: number;
  userStreamKeepaliveGraceMs: number;
  userStreamHeartbeatMaxAgeMs: number;
  userStreamKeepaliveMaxAgeMs: number;
  userStreamHealthPublishIntervalMs: number;
  userStreamHealthTtlMs: number;
  userStreamReconnectBaseDelayMs: number;
  userStreamReconnectMaxDelayMs: number;
  userStreamReconnectAttemptsBeforeRenegotiate: number;
  userStreamSeenEventTtlMs: number;
  userStreamSeenEventCacheSize: number;
}

export const DEFAULT_REACTIVE_RUNTIME_THRESHOLDS: ReactiveRuntimeThresholds = {
  ownerLeaseTtlMs: 30_000,
  ownerRenewIntervalMs: 10_000,
  ownerSweepIntervalMs: 10_000,
  symbolRefreshIntervalMs: 30_000,
  healthPublishIntervalMs: 5_000,
  streamTickMaxAgeMs: 20_000,
  streamHeartbeatMaxAgeMs: 90_000,
  streamHealthTtlMs: 25_000,
  streamWarmupTicks: 2,
  wsPingIntervalMs: 30_000,
  wsPongTimeoutMs: 10_000,
  botActionLeaseTtlMs: 30_000,
  degradedNotifyAfterMs: 60_000,
  trailingPersistIntervalMs: 30_000,
  entryFillProbeDebounceMs: 15_000,
  coordinationCommandTimeoutMs: 2_000,
  coordinationBootstrapTimeoutMs: 5_000,
  userStreamOwnerLeaseTtlMs: 30_000,
  userStreamOwnerRenewIntervalMs: 10_000,
  userStreamSweepIntervalMs: 10_000,
  userStreamSubscriptionRefreshIntervalMs: 30_000,
  userStreamKeyExpiryMs: 3_600_000,
  userStreamKeepaliveIntervalMs: 900_000,
  userStreamKeepaliveGraceMs: 600_000,
  userStreamHeartbeatMaxAgeMs: 240_000,
  userStreamKeepaliveMaxAgeMs: 2_400_000,
  userStreamHealthPublishIntervalMs: 5_000,
  userStreamHealthTtlMs: 25_000,
  userStreamReconnectBaseDelayMs: 1_000,
  userStreamReconnectMaxDelayMs: 30_000,
  userStreamReconnectAttemptsBeforeRenegotiate: 3,
  userStreamSeenEventTtlMs: 600_000,
  userStreamSeenEventCacheSize: 500,
};
