import {
  ENTRY_ORDER_CANCEL_REASONS,
  type EntryOrderCancelReasonWire,
  type EntryOrderStatusWire,
  type EntryOrderWire,
  type EntryOrdersPageWire,
  type TradingConfigWire,
} from '@crypto-trader/shared';

export function makeFixtureEntry(overrides: Partial<EntryOrderWire>): EntryOrderWire {
  return {
    id: 'eo_default',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    mode: 'TESTNET',
    entryMode: 'LIMIT_MAKER',
    status: 'RESTING',
    quantity: 0.001,
    limitPrice: 60000,
    stopPrice: null,
    stopLimitPrice: null,
    trailingDeltaBips: null,
    referencePrice: 60500,
    plannedNotionalUsd: 60,
    clientOrderId: 'client-default',
    orderListId: null,
    orderId: null,
    placedAt: '2026-09-01T10:00:00.000Z',
    expiresAt: '2026-09-05T10:00:00.000Z',
    filledLeg: null,
    executedPrice: null,
    executedQuantity: null,
    positionId: null,
    cancelReason: null,
    settledAt: null,
    ...overrides,
  } satisfies EntryOrderWire;
}

export function makeFixtureConfig(overrides: Partial<TradingConfigWire>): TradingConfigWire {
  return {
    id: 'cfg_default',
    userId: 'user_1',
    name: 'Default bot',
    asset: 'BTC',
    pair: 'USDT',
    mode: 'TESTNET',
    buyThreshold: 0.6,
    sellThreshold: 0.4,
    stopLossPct: 2,
    takeProfitPct: 4,
    minProfitPct: 0.5,
    maxTradePct: 10,
    maxConcurrentPositions: 1,
    minIntervalMinutes: 15,
    intervalMode: 'AGENT',
    orderPriceOffsetPct: 0.1,
    riskProfile: 'MODERATE',
    isRunning: true,
    lossCutEnabled: false,
    lossCutConfidenceThreshold: 0.5,
    lossCutMinLossPct: 1,
    lossCutMinEdgeRatio: 1,
    smartSizingEnabled: false,
    reduceSizeFactor: 0.5,
    deterministicGateEnabled: false,
    gatePriceChangePct: 0.5,
    nativeProtectionEnabled: true,
    closeOnProtectionFailure: false,
    stopLimitOffsetPct: 0.1,
    trailingStopEnabled: false,
    trailingStopPct: 1,
    trailingActivationPct: 1,
    partialTpEnabled: false,
    partialTpTriggerPct: 2,
    partialTpSellPct: 50,
    moveStopToBreakevenAfterPartial: false,
    maxPositionHoldMinutes: null,
    reactiveLoopEnabled: false,
    maxActionsPerHour: 6,
    minActionIntervalSec: 60,
    entryOrderMode: 'LIMIT_MAKER',
    entryOrderTtlMinutes: 60,
    entryTrailingDeltaBips: null,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  } satisfies TradingConfigWire;
}

export const TRADING_CONFIGS_FOR_ENTRIES: TradingConfigWire[] = [
  makeFixtureConfig({ id: 'cfg_btc', name: 'BTC Momentum', asset: 'BTC', pair: 'USDT' }),
  makeFixtureConfig({ id: 'cfg_eth', name: '', asset: 'ETH', pair: 'USDT' }),
];

export const ENTRY_ORDERS_ALL_STATES: EntryOrderWire[] = [
  makeFixtureEntry({
    id: 'eo_resting_oco_trailing',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    entryMode: 'OCO',
    status: 'RESTING',
    limitPrice: 61250.5,
    stopPrice: 63100,
    stopLimitPrice: 63250,
    trailingDeltaBips: 120,
    plannedNotionalUsd: 73.5,
    expiresAt: '2026-09-10T13:00:00.000Z',
  }),
  makeFixtureEntry({
    id: 'eo_resting_limit_expired',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'RESTING',
    limitPrice: 59800,
    expiresAt: '2020-01-01T00:00:00.000Z',
  }),
  makeFixtureEntry({
    id: 'eo_filled_limit_leg',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'FILLED',
    limitPrice: 59500,
    filledLeg: 'LIMIT',
    executedPrice: 59480,
    executedQuantity: 0.002,
    positionId: 'pos_1',
    settledAt: '2026-09-02T08:00:00.000Z',
  }),
  makeFixtureEntry({
    id: 'eo_filled_stop_leg_partial',
    configId: 'cfg_eth',
    symbol: 'ETHUSDT',
    entryMode: 'OCO',
    status: 'FILLED',
    limitPrice: 3300,
    stopPrice: 3450,
    stopLimitPrice: 3460,
    filledLeg: 'STOP',
    executedPrice: 3460,
    executedQuantity: 0.5,
    positionId: null,
    cancelReason: 'PARTIAL_FILL_REMAINDER',
    settledAt: '2026-09-02T09:00:00.000Z',
  }),
  makeFixtureEntry({
    id: 'eo_cancelled',
    configId: 'cfg_eth',
    symbol: 'ETHUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'CANCELLED',
    limitPrice: 3200,
    cancelReason: 'BOT_STOPPED',
    settledAt: '2026-09-03T00:00:00.000Z',
  }),
  makeFixtureEntry({
    id: 'eo_expired',
    configId: 'cfg_ghost',
    symbol: 'BTCUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'EXPIRED',
    limitPrice: 58000,
    expiresAt: '2026-09-04T00:00:00.000Z',
    settledAt: null,
  }),
  makeFixtureEntry({
    id: 'eo_missing',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'MISSING',
    limitPrice: 60200,
  }),
  makeFixtureEntry({
    id: 'eo_unknown_status',
    configId: 'cfg_btc',
    symbol: 'BTCUSDT',
    entryMode: 'LIMIT_MAKER',
    status: 'PENDING_REVIEW' as EntryOrderStatusWire,
    limitPrice: 60300,
  }),
  makeFixtureEntry({
    id: 'eo_oco_fixed',
    configId: 'cfg_eth',
    symbol: 'ETHUSDT',
    entryMode: 'OCO',
    status: 'RESTING',
    limitPrice: 3350,
    stopPrice: 3500,
    stopLimitPrice: 3510,
    trailingDeltaBips: null,
    expiresAt: '2026-09-11T00:00:00.000Z',
  }),
];

const CANCEL_REASON_VALUES: (EntryOrderCancelReasonWire | 'SOMETHING_ELSE' | null)[] = [
  ...ENTRY_ORDER_CANCEL_REASONS,
  null,
  'SOMETHING_ELSE',
];

export const ENTRY_ORDERS_ALL_CANCEL_REASONS: EntryOrderWire[] = CANCEL_REASON_VALUES.map(
  (reason, index) =>
    makeFixtureEntry({
      id: `eo_cancel_reason_${index}`,
      configId: 'cfg_btc',
      status: 'CANCELLED',
      cancelReason: reason as EntryOrderCancelReasonWire | null,
      filledLeg: 'LIMIT',
      executedPrice: 12345,
      executedQuantity: 0.01,
      positionId: 'pos_poison',
      settledAt: '2026-09-02T00:00:00.000Z',
    }),
);

export const ENTRY_ORDERS_PAGE_1: EntryOrdersPageWire = {
  items: [
    makeFixtureEntry({ id: 'eo_page1_a', configId: 'cfg_btc' }),
    makeFixtureEntry({ id: 'eo_page1_b', configId: 'cfg_btc' }),
    makeFixtureEntry({ id: 'eo_border', configId: 'cfg_eth' }),
  ],
  nextCursor: 'eo_border',
};

export const ENTRY_ORDERS_PAGE_2: EntryOrdersPageWire = {
  items: [
    makeFixtureEntry({ id: 'eo_border', configId: 'cfg_eth' }),
    makeFixtureEntry({ id: 'eo_page2_a', configId: 'cfg_eth' }),
  ],
  nextCursor: null,
};
